default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>
  timeout: 5000
  host: <%= ENV.fetch("DATABASE_HOST") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  database: <%= ENV.fetch("DATABASE_NAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default

test:
  <<: *default
  database: insurance_crm_test

demonstration:
  <<: *default

production:
  <<: *default
