default: &default
  adapter: mysql2
  pool: <%= ENV['RAILS_MAX_THREADS'] || 100 %>
  timeout: 5000
  encoding: utf8
  reconnect: true
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default
  database: insurance_crm_test

demonstration:
  <<: *default

production:
  <<: *default
